# Этап 1: Сборка React
FROM node:22-alpine AS builder
RUN npm config set registry https://registry.npmmirror.com
WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY arthub-frontend/package.json arthub-frontend/package-lock.json ./
RUN npm install

# Копируем код и собираем
COPY arthub-frontend/ ./
RUN npm run build

# Этап 2: Nginx для раздачи статики
FROM nginx:alpine

# Копируем собранный фронт
COPY --from=builder /app/dist /usr/share/nginx/html

# Копируем конфиг nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]